image: google/cloud-sdk:alpine

services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay2
  REGISTRY_IMAGE: us-central1-docker.pkg.dev
  REPOSITORY: customer-charm
  SERVICE_NAME_API: api
  VERSION_API: 0.1
  SEVICE_NAME_UI: ui
  VERSION_UI: 0.1




stages:
  - build_deploy
  # - build
  # - deploy


build_deploy:
  stage: build_deploy
  script:
    - cp $GCP_KEY /tmp/keyfile.json
    - gcloud auth activate-service-account --key-file=/tmp/keyfile.json
    - gcloud config set project $PROJECT_ID
    - gcloud builds submit --config=cloudbuild.yaml --substitutions=_PROJECT_ID=$PROJECT_ID,_REGISTRY_IMAGE=$REGISTRY_IMAGE,_REPOSITORY=$REPOSITORY,_SERVICE_NAME_API=$SERVICE_NAME_API,_VERSION_API=$VERSION_API,_SEVICE_NAME_UI=$SEVICE_NAME_UI,_VERSION_UI=$VERSION_UI .
  only:
    - main